apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web
  namespace: sample-app
spec:
  host: web.apps.lab.home.arpa
  to:
    kind: Service
    name: web
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
