apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai
  namespace: ai-gateway
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: ai-gateway-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: ai.apps.lab.home.arpa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: litellm
                port:
                  number: 4000
