apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:swares/HomeLab.git
    targetRevision: main
    path: gitops/workloads/lldap
  destination:
    server: https://kubernetes.default.svc
    namespace: lldap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
