apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-backup-secrets
  namespace: lldap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: lldap-backup-secrets
    creationPolicy: Owner
  data:
    - secretKey: restic-password
      remoteRef:
        key: secret/lab/restic
        property: password
    - secretKey: ssh-private-key
      remoteRef:
        key: secret/lab/lldap-backup
        property: ssh_private_key
