apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-ca-cert
  namespace: minio
data:
  lab-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBsTCCAVegAwIBAgIRAN53bKssljTKdZlvULLQY2AwCgYIKoZIzj0EAwIwODEW
    MBQGA1UEChMNbGFiLmhvbWUuYXJwYTEeMBwGA1UEAxMVTGFiIEhvbWUgQXJwYSBS
    b290IENBMB4XDTI2MDYyNTE2MDM0OVoXDTM2MDYyMjE2MDM0OVowODEWMBQGA1UE
    ChMNbGFiLmhvbWUuYXJwYTEeMBwGA1UEAxMVTGFiIEhvbWUgQXJwYSBSb290IENB
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8c25duQQLhXNuzAYD//hdGSWLLgb
    q1GxJgXDgQTBzGjvNQBE7+zmegsAp0F1zeKxuoKVmk7P0nH6wN9spSU5ZqNCMEAw
    DgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFDUhRVqX
    kNSPV0q366wsgxlwn6YFMAoGCCqGSM49BAMCA0gAMEUCIQCnahnm/jD8KE2+LJtQ
    L/NzAlf4OYxgUA8Li0+KzBRoWgIgOBlLs2JQnxpl/wCmHC/+FSns7MEMuKJBunN4
    XBmEM8o=
    -----END CERTIFICATE-----
